# Generated by Django 4.1.3 on 2022-11-10 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='ФИО')),
                ('title', models.CharField(max_length=200, verbose_name='Должность')),
                ('picture', models.ImageField(upload_to='aelitaapp/photos/%Y/%m/%d', verbose_name='Фото')),
            ],
            options={
                'db_table': 'Доктора',
                'ordering': ['name'],
            },
        ),
    ]
