# Generated by Django 4.1.3 on 2023-01-24 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категории',
                'verbose_name_plural': 'Категории',
                'db_table': 'categorys',
            },
        ),
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='ФИО')),
                ('title', models.CharField(max_length=200, verbose_name='Должность')),
                ('about', models.TextField(default='Информации нет', verbose_name='Подробнее')),
                ('picture', models.ImageField(upload_to='aelitaapp/photos/%Y/%m/%d', verbose_name='Фото')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Доктора',
                'verbose_name_plural': 'Доктора',
                'db_table': 'doctors',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=300, verbose_name='Название')),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
                ('id_cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aelitaapp.categorys', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Цены',
                'verbose_name_plural': 'Цены',
                'db_table': 'price',
                'ordering': ['name'],
            },
        ),
    ]
