# Generated by Django 4.1.3 on 2022-11-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aelitaapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='about',
            field=models.TextField(default='Информации нет', verbose_name='Подробнее'),
        ),
        migrations.AlterModelTable(
            name='doctors',
            table='doctors',
        ),
    ]
