# Generated by Django 4.1.3 on 2022-11-15 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aelitaapp', '0002_doctors_about_alter_doctors_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctors',
            options={'ordering': ['name'], 'verbose_name': 'Доктора', 'verbose_name_plural': 'Доктора'},
        ),
    ]
